CREATE TABLE CAR_INFO(
	MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY
	, MODEL_NAME VARCHAR(50) NOT NULL
	, PRICE INT NOT NULL
	, BRAND VARCHAR(50) NOT NULL
);

CREATE TABLE SALE_INFO(
	SALE_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BUYER VARCHAR(50) NOT NULL
	, BUYER_TEL VARCHAR(100)
	, CAR_COLOR VARCHAR(50) NOT NULL
	, SALE_DATE DATE NOT NULL
	, MODEL_NUM INT NOT NULL REFERENCES CAR_INFO (MODEL_NUM)	
);

SELECT * FROM CAR_INFO;
SELECT * FROM SALE_INFO;


-- 차량 등록 쿼리
INSERT INTO car_info (MODEL_NAME , PRICE, BRAND)
VALUES ('흉기차', 100000, '현대');


-- 차량 목록 조회 쿼리
SELECT model_num, model_name, price, brand
FROM car_info;