-- 모든 테이블을 위에서 아래로 차례대로 쭉 만들려면 커서 아무데나 두고 F9 / 오라클은 F5

CREATE TABLE JOIN_STU (
	STU_NUM INT PRIMARY KEY
	, STU_NAME VARCHAR(50)
	, MAJOR VARCHAR(50)
);

CREATE TABLE JOIN_SCORE (
	SCORE_NUM INT PRIMARY KEY
	, SCORE INT
	, STU_NUM INT
);

INSERT INTO JOIN_STU VALUES (1, '김자바', '자바전공');
INSERT INTO JOIN_STU VALUES (2, '이자바', '자바전공');
INSERT INTO JOIN_STU VALUES (3, '박자바', '자바전공');
INSERT INTO JOIN_STU VALUES (4, '윤회계', '회계전공');
INSERT INTO JOIN_STU VALUES (5, '정회계', '회계전공');
INSERT INTO JOIN_STU VALUES (6, '최회계', '회계전공');

INSERT INTO JOIN_SCORE VALUES (1, 80, 1);
INSERT INTO JOIN_SCORE VALUES (2, 70, 2);
INSERT INTO JOIN_SCORE VALUES (3, 70, 5);
INSERT INTO JOIN_SCORE VALUES (4, 85, 6);
INSERT INTO JOIN_SCORE VALUES (5, 89, 7);
INSERT INTO JOIN_SCORE VALUES (6, 77, 8);

-- 아래 쿼리의 실행결과 조회되는 데이터 수는 몇개인가?\
-- join, where을 해석 잘 할 것
SELECT STU.STU_NUM, STU_NAME, SCORE
FROM JOIN_STU STU, JOIN_SCORE SCORE
WHERE STU.STU_NUM = SCORE.STU_NUM;
-- 오라클로는 위 문법에서 OUTER 조인 가능
-- MARIADB로는 위 문법에서 OUTER 조인 불가능


-- 조인은 각 데이터베이스별 문법 존재,
-- 모든 데이터베이스에서 사용 가능한 문법 'ANSI' 문법
-- MARIADB는 MYSQL 최신 버전
-- ANSI로 작성
-- , 대신 INNER JOIN 들어옴
-- JOIN 조건은 WHERE절이 아니라 ON절에 작성
-- INNER JOIN -> JOIN 대체 가능 ( INNER 생략 가능 )
SELECT STU.STU_NUM, STU_NAME, SCORE
FROM JOIN_STU STU INNER JOIN JOIN_SCORE SCORE
ON STU.STU_NUM = SCORE.STU_NUM
WHERE STU.STU_NUM = 1;

-- JOIN은 INNER JOIN, OUTER JOIN 두 가지로 구분
-- OUTER JOIN : RIGHT OUTER JOIN, LEFT OUT JOIN
-- 가정. 모든 학생에 대한 점수를 조회

-- 모든 학생의 정보는 조회되나, 학생의 점수는가 없는 경우에는 NULL이 나옴
SELECT STU.STU_NUM, STU_NAME, IFNULL(SCORE, 0) AS SCORE
FROM JOIN_STU STU LEFT OUTER JOIN JOIN_SCORE SCORE
ON STU.STU_NUM = SCORE.STU_NUM;


SELECT STU.STU_NUM, STU_NAME, IFNULL(SCORE, 0) AS SCORE
FROM JOIN_STU STU RIGHT OUTER JOIN JOIN_SCORE SCORE
ON STU.STU_NUM = SCORE.STU_NUM;


-- 아래의 문법에서 OUTER JOIN 사용하기
SELECT STU.STU_NUM, STU_NAME, SCORE
FROM JOIN_STU STU, JOIN_SCORE SCORE
-- WHERE STU.STU_NUM = SCORE.STU_NUM; - INNER JOIN
-- WHERE STU.STU_NUM = SCORE.STU_NUM(+); - LEFT JOIN
-- WHERE STU.STU_NUM(+) = SCORE.STU_NUM; - RIGHT JOIN