-- 쇼핑몰 프로젝트 테이블 정의
-- 1. 회원정보 테이블
CREATE TABLE SHOP_MEMBER (
	MEM_ID VARCHAR(50) PRIMARY KEY
	, MEM_PW VARCHAR(100) NOT NULL
	, MEM_NAME VARCHAR(50) NOT NULL
	, MEM_TEL VARCHAR(30) UNIQUE
	, POST VARCHAR(10)
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, MEM_EMAIL VARCHAR(100)
	, MEM_ROLE VARCHAR(30) DEFAULT 'USER'
);

-- 2. 상품 카테고리 테이블
CREATE TABLE ITEM_CATEGORY(
	CATE_CODE INT AUTO_INCREMENT PRIMARY KEY
	, CATE_NAME VARCHAR(50) NOT NULL UNIQUE
);

-- 3. 상품 정보 테이블
INSERT INTO item_category VALUES (1, '인터넷/IT');
INSERT INTO item_category VALUES (2, '소설/에세이');
INSERT INTO item_category VALUES (3, '자기개발');

-- 4. 상품 이미지 정보 테이블
CREATE TABLE SHOP_ITEM(
	ITEM_CODE INT AUTO_INCREMENT PRIMARY KEY
	, ITEM_NAME VARCHAR(50) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, ITEM_INTRO VARCHAR(100)
	, ITEM_STOCK INT DEFAULT 20
	, ITEM_STATUS VARCHAR(10) DEFAULT 'FOR_SALE'
	, CATE_CODE INT NOT NULL REFERENCES ITEM_CATEGORY (CATE_CODE)
);

-- 4. 상품 이미지 정보 테이블
CREATE TABLE ITEM_IMG(
	IMG_CODE INT AUTO_INCREMENT PRIMARY KEY
	, ORIGIN_FILE_NAME VARCHAR(100) NOT NULL
	, ATTACHED_FILE_NAME VARCHAR(100) NOT NULL
	, IS_MAIN VARCHAR(5) NOT NULL
	, ITEM_CODE INT NOT NULL REFERENCES shop_item (ITEM_CODE) ON DELETE CASCADE
);


-- 5. 장바구니 정보 테이블
CREATE TABLE SHOP_CART (
	CART_CODE INT AUTO_INCREMENT PRIMARY KEY
	, ITEM_CODE INT NOT NULL REFERENCES shop_item (ITEM_CODE) ON DELETE CASCADE
	, CART_CNT INT NOT NULL
	, MEM_ID VARCHAR(50) NOT NULL REFERENCES shop_member (MEM_ID) ON DELETE CASCADE
	, CART_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 6. 구매 정보 테이블


SELECT 
    C.CART_CODE, I.ITEM_NAME, I.ITEM_PRICE, C.CART_CNT, C.CART_DATE
FROM shop_cart C, SHOP_ITEM I 
WHERE C.ITEM_CODE = I.ITEM_CODE
ORDER BY 
    C.CART_DATE DESC;


SELECT cart_code, cart_cnt, mem_id, 
DATE_FORMAT(cart_date, '%Y-%m-%d %H-%i')
			, item_name, item_price, attached_file_name
FROM shop_cart c, shop_item i, item_img img
WHERE c.item_code = i.item_code
AND c.item_code = img.item_code
AND MEM_ID = 'java'
AND IS_MAIN = 'Y';

-- 내 장바구니에 현재 선택한 상품이 있는지 확인하는 쿼리
SELECT CART_CODE
FROM SHOP_CART
WHERE ITEM_CODE = 1
AND MEM_ID = 'JAVA';

-- 내 장바구니 상품의 수량 및 날짜 변경
-- UPDATE 할때는 DATE 값이 자동으로 입력되지 않음 ( DEFALUT 값 )
UPDATE TABLE shop_cart
SET CART_CNT = CART_CNT + 1, CART_DATE
WHERE ITEM_CODE = 1
AND MEM_ID = 'JAVA';	

DELETE FROM shop_cart;
DELETE FROM shop_item;