-- 질병 임시 데이터
INSERT INTO DISEASE_CATEGORY VALUES ('001', '감기', 10000);
INSERT INTO DISEASE_CATEGORY VALUES ('002', '코로나', 30000);
INSERT INTO DISEASE_CATEGORY VALUES ('003', '장염', 20000);
INSERT INTO DISEASE_CATEGORY VALUES ('004', '독감', 15000);

-- 진료과 임시 데이터
INSERT INTO medi_dept VALUE (1, '내과');
INSERT INTO medi_dept VALUE (2, '외과');
INSERT INTO medi_dept VALUE (3, '신경과');

UPDATE recep_info
SET recep_STATUS = '대기중';


CREATE TABLE DESK(
   DESK_NUM INT PRIMARY KEY NOT NULL AUTO_INCREMENT
   , TRE_NUM INT REFERENCES info_treat(TRE_NUM) ON DELETE CASCADE
   , DESK_DATE DATETIME DEFAULT CURRENT_TIMESTAMP()
   , DESK_PRICE INT 
   , IS_PAY VARCHAR(10) DEFAULT 'N'
);

DROP TABLE desk;

INSERT INTO DESK (TRE_NUM, DESK_PRICE, IS_PAY)
VALUES (2, 75000, 'N');